const homeItemContainer = [
  {
    itemId: "1",
    itemImage: <img src="1.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "2",
    itemImage: <img src="2.jpg" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "30-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "3",
    itemImage: <img src="3.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-70% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "4",
    itemImage: <img src="4.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "80-90% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "5",
    itemImage: <img src="5.jpg" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "30-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "6",
    itemImage: <img src="6.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "7",
    itemImage: <img src="7.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "60-70% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "8",
    itemImage: <img src="8.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "50-70% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "9",
    itemImage: <img src="9.jpg" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "10",
    itemImage: <img src="10.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "11",
    itemImage: <img src="11.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "12",
    itemImage: <img src="12.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "13",
    itemImage: <img src="13.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "14",
    itemImage: <img src="14.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "15",
    itemImage: <img src="15.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "16",
    itemImage: <img src="16.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "17",
    itemImage: <img src="17.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "18",
    itemImage: <img src="18.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "19",
    itemImage: <img src="19.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
  {
    itemId: "20",
    itemImage: <img src="20.avif" />,
    itemName: "WHF Casual Wear",
    itemDiscount: "40-50% OFF",
    itemSlogan: "SHOP NOW",
  },
];
export default homeItemContainer;
