const womenItemContainer = [
  {
    itemId: "1",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "2",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "3",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "4",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "5",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "6",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "7",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "8",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "9",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "10",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "11",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "12",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "13",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "14",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
  {
    itemId: "15",
    itemImage: <img src="3.avif" alt="" />,
    itemName: "LC Waikiki",
    itemType: "Men Addidas Lower",
    itemCurrent: "Rs. 450",
    itemOriginal: "Rs. 1099",
  },
];
export default womenItemContainer;
